### ISSUE TITLE
Should bs-containers have first-class cross-platform support?

### ISSUE THREAD

**Issue by glennsl** [reasonml-old/bs-containers#20]
Note: cross-platform in this context means BuckleScript + Native.

* Some (especially @chenglou I think) have voiced strong interest in having bs-containers be cross-platform, and perhaps eventually even be (part of) a std lib for reason
* There's an overlap between bs-container and immutable.re. @bordoley has expressed interest in moving the overlapping parts of immutable.re to bs-containers (encouraged by @jordwalke and @chenglou I believe) on the condition that bs-containers has proper cross-platform support.
* Having a cross-platform library called bs-something is just plain weird and confusing isn't it? If we go cross-platform, we should rethink the name
* The current focus is on BuckleScript, but as I understand it actually copmpiles effortlessly to native too.

What do we need to accomplish this?
* A native build process
* Cross platform unit tests
* CI for both platforms

**Comment by chenglou** [comment]
Cross-platform, aside from the code itself, means some of the build processes. cc @bsansouci who's working on bsb native. It's more than that though; it'd probably need ocamlfind/meta support. But this is (and should be) entirely independent of bs-container.

Yes, we've incurred our own churn by adding yet another stdlib (well, not _really_ since it's a fork), we should at least do everyone a favor and have this be the default for Reason & BS everywhere.

We can keep this named bs-container, and keep it under BuckleTypes, until the native compilation & sharing story is ready. Don't wanna over-advertise native compatibility. But when the time comes, here's a list of new names: https://github.com/reasonml/ideas-for-project-names-starting-with-re

**Comment by bsansouci** [comment]
@chenglou If this is a pile of ocaml code (read: only ocaml code) then we shouldn't need ocamlfind/meta support. Using ocamlfind would be to support opam, since it can read the `META` file that opam projects have. `META` is pretty general and could also be used for C compilation (in theory, I don't have a proof of that). 

So if we don't have browser specific code or C code in there, we shouldn't need anything fancy from the build system :)

**Comment by glennsl** [comment]
The list is missing my favorite, "rebase"...

Also, cc @bobzhang

**Comment by glennsl** [comment]
Would this in any way restrict our ability to generate efficient code for bs or native? How do we provide separate implementations if we need to?

**Comment by bobzhang** [comment]
I wish we can get something production ready before we explore other backends, it's always good to be focused first

**Comment by chenglou** [comment]
We'll definitely get this ready for js first since that's where the focus is

**Comment by glennsl** [comment]
Even if we decide to do js first, there's still design considerations that would be useful to have in mind to eventually be able to fully support native. If we let immutable.re do its own thing for now, how will we eventually merge it, if we want to do so?

Otherwise I agree with focusing on js first.

**Comment by bobzhang** [comment]
Let's focus on JS first, if we do have strong demand to provide native support, then it means we already reach some popularity, then it would be a happy problem to solve.
Keep in mind we are still working hard to make the JS story easy to sell : )

**Comment by jordwalke** [comment]
@bsansouci

> "If this is a pile of ocaml code (read: only ocaml code) then we shouldn't need ocamlfind/meta support. Using ocamlfind would be to support opam, since it can read the META file that opam projects have. "

META isn't about opam actually. META is a general purpose convention for allowing any two native ocaml packages to be able to work with each other regardless of what build system them use. If we would like bscontainers to work with native we will need it to include a META file at build time. It's not too hard. You can even write it by hand for the package and manually keep it up to date. I only mention it because it really is an important part of any package that wants to work with native. Immutable.re includes META for example.

**Comment by dorafmon** [comment]
I also agree that we should focus on getting the JS story complete first, with the goal of supporting a native build later. I think the question is more about **when** should we start trying to support native. IMHO, this should be a test ground for `bsb native`, so when `bsb native` gets merged into the main BS repo, we will start trying to support native build here.
